import { z } from 'zod';
import { AlertSource, AlertStatus, IncidentSeverity } from '../types';

// The internal, source-agnostic alert every webhook receiver normalises
// into. Everything downstream of ingestion only ever sees this shape.
export const NormalizedAlertSchema = z.object({
  // Generated by ingestion per accepted alert. Doubles as the idempotency
  // key for incident creation, so an SQS redelivery can't create a second
  // incident.
  alertId: z.string().uuid(),
  tenantId: z.string().uuid(),
  source: z.nativeEnum(AlertSource),
  status: z.nativeEnum(AlertStatus),
  serviceName: z.string().min(1).max(100),
  severity: z.nativeEnum(IncidentSeverity),
  title: z.string().min(1).max(500),
  description: z.string().max(5000).nullable(),
  labels: z.record(z.string()),
  firedAt: z.string().datetime({ offset: true }),
  resolvedAt: z.string().datetime({ offset: true }).nullable(),
  // SHA-256(tenantId | serviceName | normalised title). Same alert from
  // any source → same fingerprint; used for dedup and for matching a
  // "resolved" notification to the open incident it closes.
  fingerprint: z.string().length(64),
  // Set when this alert belongs to an alert storm; all alerts sharing a
  // stormKey are grouped into one P1 incident.
  stormKey: z.string().max(128).nullable(),
  isStormSummary: z.boolean(),
  rawPayload: z.record(z.unknown()),
});

export type NormalizedAlert = z.infer<typeof NormalizedAlertSchema>;
